### ISSUE TITLE
Failed to connect port 8000 after deployment

### ISSUE THREAD

**Issue by stvlynn** [jaypyles/FreeAskInternet-API#1]
curl: (7) Failed to connect to localhost port 8000: Connection refused

**Comment by jaypyles** [comment]
Ports aren't exposed by default, either containerize what is interacting with the api and reference the container name in the url: `searchbackend:8000`, or expose the ports locally in the docker-compose.yml.

```yml
backend:
    image: jpyles0524/freeaskinternetapi:latest
    build:
      context: .
    container_name: searchbackend
    ports:
       - 8000:8000
    depends_on:
      - llm-freegpt35
    restart: on-failure
    networks:
      - search
```
